---
name: Ubuntu jammy Base Image
version: dev
slug: ubuntu-base
description: Docker Ubuntu jammy base images used by Home Assistant Community Add-ons.
url: https://github.com/hassio-addons/addon-ubuntu-base
arch:
  - aarch64
  - amd64
  - armv7
